name: DEV - Build 
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Please select your repo'
        required: true
        type: choice
        options:
         - client
         - service
  push:
    branches:
      - main
    paths:
      - "packages/backend/**"
      - "packages/frontend/**"
      
run-name: Deploy ${{ inputs.repo}} to DEV by @${{ github.actor }}

env:
  # NAMESPACE_PREFIX: ${{ github.event.inputs.repo }}
  # APP_NAME: mychannel-${{ github.event.inputs.repo }}-sale-payment
  OWNER_NAME: corp-ais
  IMAGE_TAG: 0.0.1-SNAPSHOT
  
jobs:
  Build:
    name: Deploy "$NAMESPACE_PREFIX" to DEV by @${{ github.actor }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          backend:
            - "packages/backend/**"
          frontend:
            - "packages/frontend/**"
            
    - name: backend path was changed
      if: steps.filter.outputs.backend == 'true'
      run: |
        echo "NAMESPACE_PREFIX=service" >> $GITHUB_ENV
        echo "APP_NAME=service-sale-payment" >> $GITHUB_ENV

    - name: frontend path was changed
      if: steps.filter.outputs.frontend == 'true'
      run: |
        echo "NAMESPACE_PREFIX=client" >> $GITHUB_ENV
        echo "APP_NAME=client-sale-payment" >> $GITHUB_ENV
        
    - name: Set GITHUB_ENV
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo "NAMESPACE_PREFIX=${{ github.event.inputs.repo }}" >> $GITHUB_ENV
        echo "APP_NAME=${{ github.event.inputs.repo }}-sale-payment" >> $GITHUB_ENV

    - name: Verify env.
      run: |
          echo "NAMESPACE_PREFIX is $NAMESPACE_PREFIX"
          echo "APP_NAME is $APP_NAME"

