name: test-monorepo
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Please select your repo'
        required: true
        type: choice
        options:
         - client
         - service
  push:
    branches:
      - main
    paths:
      - "test/backend/**"
      - "test/frontend/**"

jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.repo }} to DEV by @${{ github.actor }}
    runs-on: ubuntu-latest
    env:
      NAMESPACE_PREFIX: ${{ github.event.inputs.repo }}
    steps:
      - name: Set up job environment
        run: echo "Setting up environment"

