name: DEV - Build 
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Please select your repo'
        required: true
        type: choice
        options:
         - client
         - service
  push:
    branches:
      - main
    paths:
      - "packages/backend/**"
      - "packages/frontend/**"
      
run-name: Deploy ${{ inputs.repo}} to DEV by @${{ github.actor }}

env:
  NAMESPACE_PREFIX: ${{ github.event.inputs.repo }}
  APP_NAME: mychannel-${{ github.event.inputs.repo }}-sale-payment
  OWNER_NAME: corp-ais
  IMAGE_TAG: 0.0.1-SNAPSHOT
  
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Paths-filter
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          service:
            - "packages/backend/**"
          client:
            - "packages/frontend/**"

  matrix:
    needs: build
    strategy:
      matrix:
        repo: ${{ fromJSON(needs.build.outputs.services) }}
    runs-on: ubuntu-latest

    steps:
    - name: set env for backend path was changed
      run: |
        echo ${{ matrix.repo }}

    - name: set env
      run: |
        echo "NAMESPACE_PREFIX=${{ matrix.repo }}" >> $GITHUB_ENV
        echo "APP_NAME=mychannel-${{ matrix.repo }}-sale-payment" >> $GITHUB_ENV

    - name: verify env.
      run: |
          echo "NAMESPACE_PREFIX is $NAMESPACE_PREFIX"
          echo "APP_NAME is $APP_NAME"






