name: DEV - Build 
on:
  workflow_dispatch:
    inputs:
      namespace_prefix:
        type: choice
        description: Namespace Prefix to Deploy
        required: true
        options:
          - client
          - service
  push:
    branches:
      - main
    paths:
      - "packages/backend/**"
      - "packages/frontend/**"
      
run-name: Deploy ${{ inputs.namespace_prefix}} to DEV by @${{ github.actor }}

env:
  NAMESPACE_PREFIX: ${{ github.event.inputs.namespace_prefix }}
  APP_NAME: mychannel-${{ github.event.inputs.namespace_prefix }}-sale-payment
  OWNER_NAME: corp-ais
  IMAGE_TAG: 0.0.1-SNAPSHOT
  
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    outputs:
      namespace_prefix: ${{ steps.filter.outputs.changes }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Paths-filter
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          service:
            - "packages/backend/**"
          client:
            - "packages/frontend/**"

  matrix:
    needs: build
    strategy:
      matrix:
        namespace_prefix: ${{ fromJSON(needs.build.outputs.namespace_prefix) }}
    runs-on: ubuntu-latest

    steps:
    - name: set env for backend path was changed
      run: |
        echo ${{ matrix.repo }}

    - name: set env
      run: |
        echo "NAMESPACE_PREFIX=${{ matrix.namespace_prefix }}" >> $GITHUB_ENV
        echo "APP_NAME=mychannel-${{ matrix.namespace_prefix }}-sale-payment" >> $GITHUB_ENV

    - name: verify env.
      run: |
          echo "NAMESPACE_PREFIX is $NAMESPACE_PREFIX"
          echo "APP_NAME is $APP_NAME"






