name: test-monorepo
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Please select your repo'
        required: true
        type: choice
        options:
         - client
         - service
  push:
    branches:
      - main
    paths:
      - "test/backend/**"
      - "test/frontend/**"
      
run-name: Deploy ${{ inputs.repo}} to DEV by @${{ github.actor }}

env:
  NAMESPACE_PREFIX: ${{ github.event.inputs.repo }}
  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          backend:
            - "test/backend/**"
          frontend:
            - "test/frontend/**"
            
    # run only if 'backend' files were changed
    - name: backend path were changed
      if: steps.filter.outputs.backend == 'true'
      run: |
        echo "NAMESPACE_PREFIX=service" >> $GITHUB_ENV
        echo "APP_NAME=service-sale-payment" >> $GITHUB_ENV


    # run only if 'frontend' files were changed
    - name: backend path were changed
      if: steps.filter.outputs.frontend == 'true'
      run: |
        echo "NAMESPACE_PREFIX=client" >> $GITHUB_ENV
        echo "APP_NAME=client-sale-payment" >> $GITHUB_ENV

    - name: Verify env.NAMESPACE_PREFIX
      run: |
          echo "NAMESPACE_PREFIX is $NAMESPACE_PREFIX"
          echo "APP_NAME is $APP_NAME"

