name: test-monorepo
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Please select your repo'
        required: true
        type: choice
        options:
         - client
         - service
  push:
    branches:
      - main
    paths:
      - "test/backend/**"
      - "test/frontend/**"
      
run-name: Deploy ${{ inputs.repo}} to DEV by @${{ github.actor }}

env:
  NAMESPACE_PREFIX: ${{ github.event.inputs.repo }}
  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          backend:
            - "test/backend/**"
          frontend:
            - "test/frontend/**"

    # run only if 'backend' files were changed
    - name: backend test
      if: steps.filter.outputs.backend == 'true'
      run: |
        echo "NAMESPACE_PREFIX="service" >> $GITHUB_ENV

    # run only if 'frontend' files were changed
    - name: frontend test
      if: steps.filter.outputs.backend == 'true'
      run: |
        echo "NAMESPACE_PREFIX="client" >> $GITHUB_ENV
